# https://raw.githubusercontent.com/brianegan/flutter_redux/master/.gitlab-ci.yml
stages:
  - test
  - deploy

unit_test:
  image: alpine
  stage: test
  script:
    - git clone --branch beta --depth 1 https://github.com/flutter/flutter.git
    - export PATH=$PATH:`pwd`/flutter/bin
    - flutter doctor -v
    - flutter test --coverage
    - genhtml coverage/lcov.info --output=coverage
    - dartdoc
  artifacts:
    paths:
      - coverage/
      - doc/api/

pages:
  image: alpine
  stage: deploy
  dependencies:
    - unit_test
  script:
    - mkdir public
    - mv coverage/ public/coverage/
    - mv doc/api/ public/api/
  artifacts:
    paths:
      - public
  only:
    - master