# https://raw.githubusercontent.com/brianegan/flutter_redux/master/.gitlab-ci.yml
stages:
  - documentation
  - test
  - deploy

unit_test:
  image: ubuntu
  stage: test
  script:
    - git clone --branch beta --depth 1 https://github.com/flutter/flutter.git
    - export PATH=$PATH:`pwd`/flutter/bin
    #- git clone --branch 2.1.0 --depth 1 https://github.com/dart-lang/sdk.git
    #- wget https://github.com/dart-lang/sdk/archive/2.1.0.zip
    #- wget https://github.com/flutter/flutter/archive/v0.11.9.zip
    - flutter doctor -v
    - flutter test --coverage
    #- genhtml coverage/lcov.info --output=coverage
    #- dartdoc
  artifacts:
    paths:
      - coverage/
      - doc/api/

pages:
  image: alpine
  stage: deploy
  dependencies:
    - unit_test
  script:
    - mkdir public
    - mv coverage/ public/coverage/
    - mv doc/api/ public/api/
  artifacts:
    paths:
      - public
  only:
    - master