# https://raw.githubusercontent.com/brianegan/flutter_redux/master/.gitlab-ci.yml
stages:
  - test
  - deploy

unit_test:
  image: gcr.io/flutter-cirrus/build-flutter-image:latest
  stage: test
  script:
    - apt-get install -y curl
    - flutter upgrade
    - flutter test --coverage
    - genhtml coverage/lcov.info --output=coverage
    - dartdoc
  artifacts:
    paths:
      - coverage/
      - doc/api/

pages:
  image: alpine
  stage: deploy
  dependencies:
    - unit_test
  script:
    - mkdir public
    - mv coverage/ public/coverage/
    - mv doc/api/ public/api/
  artifacts:
    paths:
      - public
  only:
    - master